pipelines:
  branches:
   main:
    - step:
        name: Deploy to test
        deployment: test
        script:
          - chown -R 165536:165536 $BITBUCKET_CLONE_DIR
          - pipe: microsoft/azure-static-web-apps-deploy:main
            variables:
                APP_LOCATION: '$BITBUCKET_CLONE_DIR/packages/next'
                OUTPUT_LOCATION: '$BITBUCKET_CLONE_DIR/packages/next/.next'
                APP_BUILD_COMMAND: 'npm run build'
                API_TOKEN: $deployment_token
                CONFIGFILE_LOCATION: '$BITBUCKET_CLONE_DIR/packages/next/staticwebapp.config.json'
                BUILD_TIMEOUT_IN_MIN: 15